Algoritmo "SistemaRGB"

Var
cor: caractere

Inicio
Escreva("Digite R ou G, ou B ")
leia(cor)
       se(cor = "R")entao
       escreva("A cor escolhida é o vermelho")
senao
       se(cor = "G")entao
       escreva("A cor escolhida é a verde")
       
senao
       se(cor = "B")entao
       escreva("A cor escolhida é a azul")
senao
       escreva("Voce digitou um caractere invalido ")
       fimse
     fimse
    fimse
Fimalgoritmo